server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    jest:
      uris: http://121.199.40.167:9200
  rabbitmq:
    host: 121.199.40.167
    username: leishuai
    password: 871190
    virtual-host: /leishuai