server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 121.199.40.167
  rabbitmq:
    host: 121.199.40.167
    virtual-host: /leishuai
    username: leishuai
    password: 871190
auth:
  jwt:
    publicKeyPath: D:\\packageLocal\\ideaWorkHome\temp\\rsa.pub
    cookieName: GMALL_TOKEN


#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000