server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
auth:
  jwt:
    publicKeyPath: D:\\packageLocal\\ideaWorkHome\temp\\rsa.pub
    privateKeyPath: D:\\packageLocal\\ideaWorkHome\temp\\rsa.pri
    expire: 180
    cookieName: GMALL_TOKEN
    secret: leishuai**&&%%%**@@@