server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 121.199.40.167:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.199.40.167:3306/guli_ums
    username: root
    password: 871190
  redis:
    host: 121.199.40.167

mybatis-plus:
  mapper-locations: classpath:mapper/ums/**/*.xml # 读取映射文件
  global-config:
    db-config:
      id-type: auto # 默认使用数据库自增
